package com.myerp;

public enum MenuItem {
	SOURCE_LIST, SESSION_LIST, SESSION_DETAIL, JOB_LIST, NODE_LIST, NODE_SETTING, ACCOUNT_LIST, SESSION_CONTENT, REPORT_HOME, LOG_LIST, SETTING_DESTINATION, SETTING_PROFILE_PARAMETER, SETTING_PROFILE, SETTING_PROFILE_GROUP

}